name: Pull Zhihu to updates.json

on:
  schedule:
    - cron: "*/30 * * * *"   # 每 30 分钟（UTC）
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # ✅ 允许用 GITHUB_TOKEN 推回
          fetch-depth: 0              # ✅ 取完整历史，避免推送冲突
          ref: ${{ github.ref_name }} # ✅ 在触发分支上工作

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pull & Transform
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
          MAX_ITEMS: "150"
          EXCERPT_LEN: "180"
        run: |
          set -e
          node -e "console.log('Node version', process.version)"
          node scripts/pull_updates.js

      - name: Accumulate into updates-all.json
        run: |
          set -e
          node scripts/accumulate_updates.js
          echo "--- head updates-all.json ---"
          head -c 1200 data/updates-all.json || true
          echo

      - name: Commit & Push changes (updates + updates-all)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          git pull --rebase origin "$BRANCH" || true

          # 只提交这两个文件（和你的需求一致）
          git add data/updates.json data/updates-all.json

          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: accumulate updates into updates-all.json"
          git push origin "$BRANCH"
