name: Pull Zhihu to updates.json

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pull & Transform
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
          MAX_ITEMS: "50000"
          EXCERPT_LEN: "180"
          LATEST_KEEP: "50"
        run: |
          node -e "console.log('Node', process.version)"
          node scripts/pull_updates.js

      # —— 关键：打印结果，确认不是 [] —— 
      - name: Show results
        run: |
          echo "--- updates-all.json (size bytes) ---"
          wc -c data/updates-all.json || true
          echo "--- head updates-all.json ---"
          head -c 1200 data/updates-all.json || true
          echo
          echo "--- updates.json (size bytes) ---"
          wc -c data/updates.json || true
          echo "--- head updates.json ---"
          head -c 1200 data/updates.json || true

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/updates.json data/updates-all.json
            git commit -m "chore: refresh updates data"
            git push
          else
            echo "No changes"
          fi
