name: Pull RSS → updates-all.json & updates.json

on:
  schedule:
    - cron: "*/30 * * * *"   # 每 30 分钟跑一次（UTC）；按需调整频率
  workflow_dispatch: {}       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 如果没有 package.json，可以跳过安装依赖这步
      - name: Install deps (optional)
        run: npm ci || true

      - name: Pull & Merge RSS to JSON
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }} # 见下方“Secrets 格式”
          EXCERPT_LEN: "180"
          LATEST_KEEP: "50"                 # updates.json 保留条数（供 banner）
          MAX_ITEMS: "50000"                # 全量库上限（updates-all.json）
        run: node scripts/pull_updates.js

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/updates.json data/updates-all.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: refresh updates-all.json & updates.json"
            git push
          fi
