name: Pull Zhihu to updates.json

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ 允许推送到当前仓库

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # ✅ 用 GITHUB_TOKEN 推回本仓库
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Echo RSS_URLS length (debug)
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
        run: |
          echo "RSS_URLS length: ${#RSS_URLS}"
          echo "RSS_URLS head: ${RSS_URLS:0:200}"

      - name: Check RSS_URLS lines (sanitized)
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
        run: |
          echo "----- RAW COUNT -----"
          echo "$RSS_URLS" | awk 'NF>0{c++} END{print "non-empty lines:", c+0}'
          echo "----- SHOW PLATFORMS ONLY -----"
          echo "$RSS_URLS" | sed -E 's#^([^ ]+) .*#\1#g' | sed -E 's#^https?://.*#(no platform)#g' | head -n 50

      - name: Curl first 1-2 feeds (HEAD/GET)
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
        run: |
          set -e
          URL1=$(echo "$RSS_URLS" | sed -E 's#^[^ ]+ ##' | grep -E '^https?://' | head -n1)
          [ -z "$URL1" ] && URL1=$(echo "$RSS_URLS" | head -n1)
          echo "Test URL: $URL1"
          curl -I -L --max-time 15 "$URL1" || true
          curl -L --max-time 15 --range 0-1024 "$URL1" || true

      - name: Pull & Transform
        env:
          RSS_URLS: ${{ secrets.RSS_URLS }}
          MAX_ITEMS: "50000"
          EXCERPT_LEN: "180"
          LATEST_KEEP: "50"
        run: |
          node -e "console.log('Node', process.version)"
          node scripts/pull_updates.js

      - name: Show results
        run: |
          echo "--- updates-all.json size ---"
          wc -c data/updates-all.json || true
          echo "--- head updates-all.json ---"
          head -c 1200 data/updates-all.json || true
          echo
          echo "--- updates.json size ---"
          wc -c data/updates.json || true
          echo "--- head updates.json ---"
          head -c 1200 data/updates.json || true

      # ✅ 新增：把生成的文件提交回仓库（仅当有变化时）
      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 只把 data 下的结果文件加入
          git add data/updates.json data/updates-all.json 2>/dev/null || true

          # 如果没有变化就跳过提交
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update RSS outputs (updates.json / updates-all.json)"
          git push
